apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-restaurant-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog-restaurant-product
  template:
    metadata:
      labels:
        app: dog-restaurant-product
    spec:
      hostname: dog-restaurant-product
      serviceAccountName: dog-service-account
      containers:
      - name: dog-restaurant-product
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/dog-restaurant-product:latest
        resources:
          requests:
            cpu: 100m
            memory: "1024Mi"
          limits:
            cpu: 1000m
            memory: "2048Mi"
        ports:
        - containerPort: 3000
        env:
        - name: AWS_REGION
          value: "us-east-1"  
      automountServiceAccountToken: false 
#        - name: DB_NAME
#          value: "${DB_NAME}"
#        - name: DB_PORT
#          value: "${DB_PORT}"    
#        - name: DB_USER
#          value: "${DB_USER}"     
#        - name: DB_PASSWORD
#          value: "${DB_PASSWORD}"
#        - name: DB_HOST
#          value: "${DB_HOST}"